Get all users for a space or organization
contentful/contentful-management.rb pull request #226
Opened 2021-05-25 15:52 UTC by rubydog

Adds ability to retrieve all users in a space or organisation. Please refer to https://www.contentful.com/developers/docs/references/user-management-api/#/reference/users for more details.

Fixes #224

2021-05-26 07:14 UTC, dlitvakb requested changes
Needs docs changes, code is good

2021-05-26 07:14 UTC, dlitvakb commented on lib/contentful/management/version.rb
> +    VERSION = '3.0.1'.freeze
Version bump should be done on the release commit, also it should be `3.1.0` as this is a minor version bump, and not a bugfix.

2021-05-31 07:42 UTC, dlitvakb approved these changes

2021-05-31 07:43 UTC, merged

2021-06-08 18:00 UTC, ghepting commented on lib/contentful/management/organization_user_methods_factory.rb
> +      def all
this method needs to accept parameters such as limit, etc as the other .all interfaces across other resources types accept.

2021-06-10 10:04 UTC, rubydog commented on lib/contentful/management/organization_user_methods_factory.rb
> +      def all
@ghepting thanks for flagging it. I will take a look at it today.

2021-06-10 12:01 UTC, ghepting commented on lib/contentful/management/organization_user_methods_factory.rb
> +      def all
Great, thanks again for your efforts here. Really want to see these ruby SDKs become more first-class citizens in the Contentful developer toolkits  :)