address deprecation of URI.escape in uri v0.10.1 (see: https://github.com/ruby/uri/pull/9)
contentful/contentful-management.rb pull request #252
Opened 2022-12-08 20:25 UTC by ghepting

addresses issue 251 https://github.com/contentful/contentful-management.rb/issues/251 

cc: @rubydog

2022-12-09 06:53 UTC, rubydog requested changes

2022-12-09 06:53 UTC, rubydog commented on lib/contentful/management/version.rb
> +    VERSION = '3.6.1'.freeze
Thanks for the PR @ghepting. Can you please undo the code changes in this line?

2022-12-09 13:50 UTC, ghepting commented on lib/contentful/management/version.rb
> +    VERSION = '3.6.1'.freeze
sure, sorry. was just trying to prep the patch release for you, too :)

2022-12-09 13:51 UTC, ghepting commented on lib/contentful/management/version.rb
> +    VERSION = '3.6.1'.freeze
updated with no changes to CHANGELOG.md and version.rb

2022-12-14 14:20 UTC, rubydog approved these changes

2022-12-14 14:21 UTC, merged